# Generated by Django 3.2.10 on 2022-02-10 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('language', models.CharField(choices=[('cpp', 'C++'), ('javascript', 'JavaScript'), ('python', 'Python'), ('c', 'C language'), ('java', 'Java'), ('css', 'CSS'), ('text', 'Plain Text'), ('php', 'PHP'), ('git', 'Git'), ('shell', 'terminal'), ('django', 'Django'), ('jinja', 'Jinja'), ('docker', 'Docker'), ('powershell', 'PowerShell'), ('nginx', 'Nginx'), ('mongodb', 'MongoDB'), ('markup', 'HTML'), ('matlab', 'MATLAB'), ('json', 'JSON'), ('graphql', 'GraphQL'), ('pug', 'PUG'), ('jsx', 'JSX'), ('regex', 'Regular Expression'), ('sass', 'SASS'), ('sql', 'SQL'), ('typescript', 'TypeScript'), ('vim', 'VIM')], max_length=50)),
                ('code', models.TextField()),
            ],
        ),
    ]
